<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\admin\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.fee.
 *
 * Los siguientes son los campos de la tabla 'public.fee':
 * @property integer $id
 * @property string $sentai_id
 * @property string $fee_descriptions

 * Los siguientes son las relaciones de este modelo :

 * @property Agency[] $array_agency
 * @property Bank[] $array_bank
 * @property Fee_details[] $array_fee_details
 **/



class Fee extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.fee';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_agency','array_bank','array_fee_details'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Fee';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'sentai_id',
      'fee_descriptions'
    ];


	 /**
     * 
     * Get array_agency
     */
	  public function array_agency()
		{
			return $this->hasMany(Agency::class,'fee_id','id');
		}

	 /**
     * 
     * Get array_bank
     */
	  public function array_bank()
		{
			return $this->hasMany(Bank::class,'fee_id','id');
		}

	 /**
     * 
     * Get array_fee_details
     */
	  public function array_fee_details()
		{
			return $this->hasMany(Fee_details::class,'fee_id','id');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'sentai_id' =>'required|max:256',
                'fee_descriptions' =>'required|max:40'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.fee,id,'.$this->id.',id',
                'sentai_id' =>'required|max:256',
                'fee_descriptions' =>'required|max:40'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

