<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\admin\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.fee_details.
 *
 * Los siguientes son los campos de la tabla 'public.fee_details':
 * @property integer $id
 * @property string $fee_type
 * @property integer $range_init
 * @property integer $range_end
 * @property integer $fee_value
 * @property integer $fee_id

 * Los siguientes son las relaciones de este modelo :

 * @property Fee $fee
 **/



class Fee_details extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.fee_details';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['fee'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Fee_details';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'fee_type',
      'range_init',
      'range_end',
      'fee_value',
      'fee_id'
    ];

	 /**
     * Get the Fee
     */
	  public function fee()
		{
			return $this->belongsTo(Fee::class,'fee_id','id');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'fee_type' =>'required|max:1',
                'range_init' =>'nullable',
                'range_end' =>'required',
                'fee_value' =>'required',
                'fee_id' =>'required|exists:'.$this->connection.'.public.fee,id'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.fee_details,id,'.$this->id.',id',
                'fee_type' =>'required|max:1',
                'range_init' =>'nullable',
                'range_end' =>'required',
                'fee_value' =>'required',
                'fee_id' =>'required|exists:'.$this->connection.'.public.fee,id'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

