<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\report\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.consiliation_bank_view.
 *
 * Los siguientes son los campos de la tabla 'public.consiliation_bank_view':
 * @property string $bank_name
 * @property integer $id
 * @property string $state_code
 * @property integer $count
 * @property integer $total_amount
 * @property integer $total_fee
 * @property string $min
 * @property string $max_date

 * Los siguientes son las relaciones de este modelo :

 **/



class Consiliation_bank_view extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.consiliation_bank_view';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'bank_name';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


/**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'string';

    const RELATIONS = [];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Consiliation_bank_view';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'bank_name',
      'id',
      'state_code',
      'count',
      'total_amount',
      'total_fee',
      'min',
      'max_date'
    ];



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'bank_name' =>'nullable|max:40|unique:'.$this->connection.'.public.consiliation_bank_view',
                'id' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view',
                'state_code' =>'nullable|max:4|unique:'.$this->connection.'.public.consiliation_bank_view',
                'count' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view',
                'total_amount' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view',
                'total_fee' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view',
                'min' =>'nullable|date|unique:'.$this->connection.'.public.consiliation_bank_view',
                'max_date' =>'nullable|date|unique:'.$this->connection.'.public.consiliation_bank_view'
            ],
            'update'=>[
                'bank_name' =>'nullable|max:40|unique:'.$this->connection.'.public.consiliation_bank_view,bank_name,'.$this->bank_name.',bank_name',
                'id' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view,id,'.$this->bank_name.',bank_name',
                'state_code' =>'nullable|max:4|unique:'.$this->connection.'.public.consiliation_bank_view,state_code,'.$this->bank_name.',bank_name',
                'count' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view,count,'.$this->bank_name.',bank_name',
                'total_amount' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view,total_amount,'.$this->bank_name.',bank_name',
                'total_fee' =>'nullable|unique:'.$this->connection.'.public.consiliation_bank_view,total_fee,'.$this->bank_name.',bank_name',
                'min' =>'nullable|date|unique:'.$this->connection.'.public.consiliation_bank_view,min,'.$this->bank_name.',bank_name',
                'max_date' =>'nullable|date|unique:'.$this->connection.'.public.consiliation_bank_view,max_date,'.$this->bank_name.',bank_name'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

