<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\report\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.deposit_for_payment.
 *
 * Los siguientes son los campos de la tabla 'public.deposit_for_payment':
 * @property integer $id
 * @property string $issuing_bank
 * @property string $agency_name
 * @property string $bank_name
 * @property integer $total_transaction
 * @property integer $total_amount
 * @property integer $total_fee
 * @property string $min
 * @property string $max_date

 * Los siguientes son las relaciones de este modelo :

 **/



class Deposit_for_payment extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.deposit_for_payment';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


/**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = [];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Deposit_for_payment';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'issuing_bank',
      'agency_name',
      'bank_name',
      'total_transaction',
      'total_amount',
      'total_fee',
      'min',
      'max_date'
    ];



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'id' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment',
                'issuing_bank' =>'nullable|max:40|unique:'.$this->connection.'.public.deposit_for_payment',
                'agency_name' =>'nullable|max:40|unique:'.$this->connection.'.public.deposit_for_payment',
                'bank_name' =>'nullable|max:40|unique:'.$this->connection.'.public.deposit_for_payment',
                'total_transaction' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment',
                'total_amount' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment',
                'total_fee' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment',
                'min' =>'nullable|date|unique:'.$this->connection.'.public.deposit_for_payment',
                'max_date' =>'nullable|date|unique:'.$this->connection.'.public.deposit_for_payment'
            ],
            'update'=>[
                'id' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment,id,'.$this->id.',id',
                'issuing_bank' =>'nullable|max:40|unique:'.$this->connection.'.public.deposit_for_payment,issuing_bank,'.$this->id.',id',
                'agency_name' =>'nullable|max:40|unique:'.$this->connection.'.public.deposit_for_payment,agency_name,'.$this->id.',id',
                'bank_name' =>'nullable|max:40|unique:'.$this->connection.'.public.deposit_for_payment,bank_name,'.$this->id.',id',
                'total_transaction' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment,total_transaction,'.$this->id.',id',
                'total_amount' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment,total_amount,'.$this->id.',id',
                'total_fee' =>'nullable|unique:'.$this->connection.'.public.deposit_for_payment,total_fee,'.$this->id.',id',
                'min' =>'nullable|date|unique:'.$this->connection.'.public.deposit_for_payment,min,'.$this->id.',id',
                'max_date' =>'nullable|date|unique:'.$this->connection.'.public.deposit_for_payment,max_date,'.$this->id.',id'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

