<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\security\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.auth_permission.
 *
 * Los siguientes son los campos de la tabla 'public.auth_permission':
 * @property integer $id
 * @property string $name
 * @property integer $content_type_id
 * @property string $codename

 * Los siguientes son las relaciones de este modelo :

 * @property Auth_group_permissions[] $array_auth_group_permissions
 * @property Auth_user_user_permissions[] $array_auth_user_user_permissions
 **/



class Auth_permission extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.auth_permission';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['array_auth_group_permissions','array_auth_user_user_permissions'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Auth_permission';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'name',
      'content_type_id',
      'codename'
    ];


	 /**
     * 
     * Get array_auth_group_permissions
     */
	  public function array_auth_group_permissions()
		{
			return $this->hasMany(Auth_group_permissions::class,'permission_id','id');
		}

	 /**
     * 
     * Get array_auth_user_user_permissions
     */
	  public function array_auth_user_user_permissions()
		{
			return $this->hasMany(Auth_user_user_permissions::class,'permission_id','id');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'name' =>'required|max:255',
                'content_type_id' =>'required',
                'codename' =>'required|max:100'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.auth_permission,id,'.$this->id.',id',
                'name' =>'required|max:255',
                'content_type_id' =>'required',
                'codename' =>'required|max:100'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

