<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\services\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.log_programer.
 *
 * Los siguientes son los campos de la tabla 'public.log_programer':
 * @property integer $id
 * @property string $log_description
 * @property string $trace
 * @property string $created_at
 * @property string $system

 * Los siguientes son las relaciones de este modelo :

 **/



class Log_programer extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.log_programer';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = [];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Log_programer';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'log_description',
      'trace',
      'created_at',
      'system'
    ];



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'log_description' =>'required',
                'trace' =>'required',
                'created_at' =>'required|date',
                'system' =>'required|max:20'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.log_programer,id,'.$this->id.',id',
                'log_description' =>'required',
                'trace' =>'required',
                'created_at' =>'required|date',
                'system' =>'required|max:20'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

