<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\services\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.municipality.
 *
 * Los siguientes son los campos de la tabla 'public.municipality':
 * @property integer $id
 * @property string $municipality_code
 * @property string $municipality_name
 * @property integer $province_id

 * Los siguientes son las relaciones de este modelo :

 * @property Province $province
 * @property Payment_transaction[] $array_payment_transaction
 **/



class Municipality extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.municipality';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['province','array_payment_transaction'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Municipality';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'municipality_code',
      'municipality_name',
      'province_id'
    ];

	 /**
     * Get the Province
     */
	  public function province()
		{
			return $this->belongsTo(Province::class,'province_id','id');
		}


	 /**
     * 
     * Get array_payment_transaction
     */
	  public function array_payment_transaction()
		{
			return $this->hasMany(Payment_transaction::class,'cust_municip_id','id');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'municipality_code' =>'required|max:20',
                'municipality_name' =>'required|max:100',
                'province_id' =>'required|exists:'.$this->connection.'.public.province,id'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.municipality,id,'.$this->id.',id',
                'municipality_code' =>'required|max:20',
                'municipality_name' =>'required|max:100',
                'province_id' =>'required|exists:'.$this->connection.'.public.province,id'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

