<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\services\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.payment_transaction_error.
 *
 * Los siguientes son los campos de la tabla 'public.payment_transaction_error':
 * @property integer $id
 * @property string $error_date
 * @property string $field_related
 * @property integer $error_id
 * @property integer $transaction_id

 * Los siguientes son las relaciones de este modelo :

 * @property Payment_transaction $transaction
 * @property Rejection_error $error
 **/



class Payment_transaction_error extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.payment_transaction_error';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['transaction','error'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Payment_transaction_error';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'error_date',
      'field_related',
      'error_id',
      'transaction_id'
    ];

	 /**
     * Get the Payment_transaction
     */
	  public function transaction()
		{
			return $this->belongsTo(Payment_transaction::class,'transaction_id','id');
		}

	 /**
     * Get the Rejection_error
     */
	  public function error()
		{
			return $this->belongsTo(Rejection_error::class,'error_id','id');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'error_date' =>'required|date',
                'field_related' =>'required|max:35',
                'error_id' =>'nullable|exists:'.$this->connection.'.public.rejection_error,id',
                'transaction_id' =>'required|exists:'.$this->connection.'.public.payment_transaction,id'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.payment_transaction_error,id,'.$this->id.',id',
                'error_date' =>'required|date',
                'field_related' =>'required|max:35',
                'error_id' =>'nullable|exists:'.$this->connection.'.public.rejection_error,id',
                'transaction_id' =>'required|exists:'.$this->connection.'.public.payment_transaction,id'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

