<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\services\Models;


use App\Models\BaseModel;


/**
 * Este es la clase modelo para la tabla public.province.
 *
 * Los siguientes son los campos de la tabla 'public.province':
 * @property integer $id
 * @property string $province_code
 * @property string $province_name
 * @property integer $country_id

 * Los siguientes son las relaciones de este modelo :

 * @property Country $country
 * @property Municipality[] $array_municipality
 * @property Payment_transaction[] $array_payment_transaction
 **/



class Province extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.province';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['country','array_municipality','array_payment_transaction'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Province';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'province_code',
      'province_name',
      'country_id'
    ];

	 /**
     * Get the Country
     */
	  public function country()
		{
			return $this->belongsTo(Country::class,'country_id','id');
		}


	 /**
     * 
     * Get array_municipality
     */
	  public function array_municipality()
		{
			return $this->hasMany(Municipality::class,'province_id','id');
		}

	 /**
     * 
     * Get array_payment_transaction
     */
	  public function array_payment_transaction()
		{
			return $this->hasMany(Payment_transaction::class,'cust_prov_id','id');
		}


    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'province_code' =>'required|max:20',
                'province_name' =>'required|max:100',
                'country_id' =>'required|exists:'.$this->connection.'.public.country,id'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.province,id,'.$this->id.',id',
                'province_code' =>'required|max:20',
                'province_name' =>'required|max:100',
                'country_id' =>'required|exists:'.$this->connection.'.public.country,id'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

