<?php
/**Generate by ASGENS
*@author Amanda  
*@date Sun May 14 14:30:00 GMT-04:00 2023  
*@time Sun May 14 14:30:00 GMT-04:00 2023  
*/
namespace Modules\services\Models;


use App\Models\BaseModel;

use Modules\admin\Models\Agency;

/**
 * Este es la clase modelo para la tabla public.sentai_batch.
 *
 * Los siguientes son los campos de la tabla 'public.sentai_batch':
 * @property integer $id
 * @property string $send_date
 * @property string $state
 * @property string $sentai_trans_no
 * @property integer $agency_id
 * @property string $sentai_batch_datetime
 * @property integer $sentai_home_amount
 * @property integer $sentai_home_fee
 * @property integer $sentai_trans_amount
 * @property integer $sentai_trans_fee
 * @property string $sentai_error

 * Los siguientes son las relaciones de este modelo :

 * @property Agency $agency
 **/



class Sentai_batch extends BaseModel 
{
 /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'public.sentai_batch';

   /**
     * The connection name for the model.
     *
     * @var string|null
     */
    protected $connection = 'bd';

    /**
     * The primarykey associated with the table-model.
     *
     * @var integer
     */
    protected $primaryKey = 'id';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */

    public $timestamps = false;


    /**
     * The "type" of the auto-incrementing ID.
     *
     * @var string
     */
    protected $keyType = 'integer';

    const RELATIONS = ['agency'];
/**
     * The number of models to return for pagination.
     *
     * @var int
     */
    protected $perPage = 15;

    protected $appends = [];

    /**
     * Model Class Name
     *
     * @var string
     */
    const MODEL = 'Sentai_batch';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
      'id',
      'send_date',
      'state',
      'sentai_trans_no',
      'agency_id',
      'sentai_batch_datetime',
      'sentai_home_amount',
      'sentai_home_fee',
      'sentai_trans_amount',
      'sentai_trans_fee',
      'sentai_error'
    ];

	 /**
     * Get the Agency
     */
	  public function agency()
		{
			return $this->belongsTo(Agency::class,'agency_id','id');
		}



    protected function rules($scenario='create')
    {
          $rules=[
            'create'=>[
                'send_date' =>'required|date',
                'state' =>'required|max:2',
                'sentai_trans_no' =>'nullable',
                'agency_id' =>'nullable|exists:'.$this->connection.'.public.agency,id',
                'sentai_batch_datetime' =>'nullable|date',
                'sentai_home_amount' =>'nullable',
                'sentai_home_fee' =>'nullable',
                'sentai_trans_amount' =>'nullable',
                'sentai_trans_fee' =>'nullable',
                'sentai_error' =>'nullable'
            ],
            'update'=>[
                'id' =>'required|unique:'.$this->connection.'.public.sentai_batch,id,'.$this->id.',id',
                'send_date' =>'required|date',
                'state' =>'required|max:2',
                'sentai_trans_no' =>'nullable',
                'agency_id' =>'nullable|exists:'.$this->connection.'.public.agency,id',
                'sentai_batch_datetime' =>'nullable|date',
                'sentai_home_amount' =>'nullable',
                'sentai_home_fee' =>'nullable',
                'sentai_trans_amount' =>'nullable',
                'sentai_trans_fee' =>'nullable',
                'sentai_error' =>'nullable'
            ]
        ];
        if(!isset($rules[$scenario]))
            throw new \Exception('Scenario '.$scenario.' not exist');
        return $rules[$scenario];
    }

 protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

}

